import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import PptxGenJS from "pptxgenjs";

const MODEL = "gemini-2.5-flash";

interface Slide {
  title: string;
  bullets: string[];
  notes: string;
}

const PROMPT = (topic: string, description: string) =>
  `You are an expert educator creating a concise PowerPoint presentation about "${topic}".
${description ? `Context: ${description}` : ""}

Generate exactly 8 slides. Output ONLY valid JSON — no markdown, no code fences.

Format:
[
  {"title": "slide title", "bullets": ["point 1", "point 2", "point 3", "point 4"], "notes": "speaker notes"},
  ...
]

Rules:
- Slide 1: Title slide with topic name and 2-3 subtitle bullets
- Slides 2-7: Core content, 3-5 bullets each, educational and specific
- Slide 8: Summary / Key Takeaways with 3-4 bullets
- Each bullet should be concise (under 15 words)
- Notes should be 1-2 sentences expanding on the slide
- Output ONLY the JSON array`;

const COLORS = {
  bg: "0F172A",
  title: "46B533",
  text: "E2E8F0",
  accent: "3B82F6",
  muted: "94A3B8",
  darkBg: "1E293B",
};

function buildPptx(slides: Slide[], topic: string): PptxGenJS {
  const pptx = new PptxGenJS();
  pptx.author = "Luminary AI";
  pptx.title = topic;
  pptx.subject = `AI-generated presentation on ${topic}`;
  pptx.layout = "LAYOUT_WIDE";

  slides.forEach((slide, idx) => {
    const s = pptx.addSlide();
    s.background = { color: COLORS.bg };

    // Green accent bar at top
    s.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: "100%", h: 0.06,
      fill: { color: COLORS.title },
    });

    if (idx === 0) {
      // Title slide
      s.addText(slide.title, {
        x: 0.8, y: 1.8, w: "85%", h: 1.5,
        fontSize: 36, fontFace: "Arial",
        color: COLORS.text, bold: true,
      });
      s.addText(slide.bullets.join("\n"), {
        x: 0.8, y: 3.5, w: "85%", h: 1.5,
        fontSize: 18, fontFace: "Arial",
        color: COLORS.muted, lineSpacingMultiple: 1.4,
      });
      s.addText("Generated by Luminary AI", {
        x: 0.8, y: 6.2, w: "85%", h: 0.4,
        fontSize: 11, fontFace: "Arial",
        color: COLORS.muted, italic: true,
      });
    } else {
      // Content slide
      s.addText(slide.title, {
        x: 0.8, y: 0.4, w: "85%", h: 0.8,
        fontSize: 26, fontFace: "Arial",
        color: COLORS.title, bold: true,
      });

      // Separator line
      s.addShape(pptx.ShapeType.rect, {
        x: 0.8, y: 1.25, w: 2.5, h: 0.03,
        fill: { color: COLORS.accent },
      });

      const bulletText = slide.bullets.map((b) => ({
        text: b,
        options: {
          fontSize: 17,
          fontFace: "Arial" as const,
          color: COLORS.text,
          bullet: { code: "2022", color: COLORS.title },
          breakType: "break" as const,
          paraSpaceAfter: 10,
        },
      }));

      s.addText(bulletText, {
        x: 0.8, y: 1.5, w: "85%", h: 4.5,
        valign: "top",
        lineSpacingMultiple: 1.5,
      });

      // Slide number
      s.addText(`${idx + 1} / ${slides.length}`, {
        x: "90%", y: "93%", w: 1, h: 0.3,
        fontSize: 9, fontFace: "Arial",
        color: COLORS.muted, align: "right",
      });
    }

    if (slide.notes) {
      s.addNotes(slide.notes);
    }
  });

  return pptx;
}

export async function POST(request: NextRequest) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: "GEMINI_API_KEY is not configured." }, { status: 500 });
  }

  let topic: string;
  let description: string;
  try {
    const body = await request.json();
    topic = body.topic?.trim();
    description = body.description?.trim() ?? "";
    if (!topic) throw new Error("missing topic");
  } catch {
    return NextResponse.json({ error: "topic is required" }, { status: 400 });
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: MODEL,
      generationConfig: { temperature: 0.4, maxOutputTokens: 2000 },
    });

    const result = await model.generateContent(PROMPT(topic, description));
    const raw = result.response.text().trim();
    const jsonStr = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
    const slides: Slide[] = JSON.parse(jsonStr);

    if (!Array.isArray(slides) || slides.length === 0) {
      throw new Error("Invalid slide data from Gemini");
    }

    const pptx = buildPptx(slides, topic);
    const buffer = await pptx.write({ outputType: "nodebuffer" }) as Buffer;
    const bytes = new Uint8Array(buffer);

    return new NextResponse(bytes, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${topic.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_")}_slides.pptx"`,
        "Content-Length": String(bytes.length),
      },
    });
  } catch (err) {
    console.error("Slides API error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to generate slides" },
      { status: 502 },
    );
  }
}
